# Generated by Django 6.0.4 on 2026-04-28 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name_fr', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='VisaCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('BLS', 'BLS International'), ('TLScontact', 'TLScontact'), ('VFS', 'VFS Global')], max_length=30)),
                ('city', models.CharField(max_length=80)),
                ('address', models.TextField(blank=True)),
                ('url_booking', models.URLField()),
                ('url_check', models.URLField(blank=True)),
                ('check_interval', models.SmallIntegerField(default=5, help_text='Minutes entre chaque vérification')),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centers', to='monitoring.country')),
            ],
            options={
                'ordering': ['platform', 'country__name_fr'],
                'unique_together': {('platform', 'country', 'city')},
            },
        ),
        migrations.CreateModel(
            name='MonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('slots_found', models.SmallIntegerField(default=0)),
                ('slots_new', models.SmallIntegerField(default=0)),
                ('http_status', models.SmallIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='monitoring.visacenter')),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('label_fr', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_types', to='monitoring.country')),
            ],
            options={
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='VisaRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Surveillance active'), ('slot_found', 'Créneau trouvé'), ('booked', 'Réservé'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('expired', 'Expiré')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('normal', 'Normal'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('desired_date_from', models.DateField()),
                ('desired_date_to', models.DateField(blank=True, null=True)),
                ('preferred_time_from', models.TimeField(blank=True, null=True)),
                ('preferred_time_to', models.TimeField(blank=True, null=True)),
                ('num_applicants', models.SmallIntegerField(default=1)),
                ('applicant_name', models.CharField(blank=True, max_length=120)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('slot_found_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='monitoring.visacenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('visa_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.visatype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField()),
                ('slot_time', models.TimeField(blank=True, null=True)),
                ('available_seats', models.SmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('taken', 'Pris'), ('expired', 'Expiré')], default='available', max_length=15)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='monitoring.visacenter')),
                ('visa_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.visatype')),
            ],
            options={
                'ordering': ['slot_date', 'slot_time'],
                'unique_together': {('center', 'slot_date', 'slot_time')},
            },
        ),
    ]
